plugins:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 120

RSpec/MultipleExpectations:
  Max: 3

RSpec/MultipleMemoizedHelpers:
  Max: 10
