
default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: test_task_6uud_dev
  host: dpg-d4oke44hg0os73dic6u0-a.oregon-postgres.render.com
  username: test_task_6uud_user
  password: <%= ENV.fetch("DB_PASSWORD") %>
  port: 5432


test:
  <<: *default
  database: test_task_6uud_test
  host: dpg-d4oke44hg0os73dic6u0-a.oregon-postgres.render.com
  username: test_task_6uud_user
  password: <%= ENV.fetch("DB_PASSWORD") %>
  port: 5432


production:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
